[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Chaff"
version = "1.1"
authors = [
  { name="Invizabel"},
]
description = "Secure overwrite tool utilizing NIST 800-88 Revision 2 (https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-88r2.pdf)"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
"Homepage" = "https://github.com/Invizabel/Chaff"
"Bug Tracker" = "https://github.com/Invizabel/Chaff"
